### ISSUE TITLE
Unit and regression testing plan

### ISSUE THREAD

**Issue by rickecon** [open-source-economics/OG-USA#309] opened 2017-07-17 14:26 UTC
This issue it outlines the steps necessary to incorporate the best practices of unit testing and regression testing into development of the `OG-USA` model. Below is a proposed outline of the sequential steps for updating `OG-USA` automatic testing.

1. Write code for `pytest` to test each function in the `OG-USA` model
    - This testing includes the  `get_TPI()` function.
    - We should measure and report code coverage.
2. Update `Travis CI` to run some subset of the `pytest` tests.  
    - We'll want to keep the `Travis CI` testing under 15 minutes of run time.
3. Create regression tests that have standardized output.  See `OG-USA` Issue #232  
    - Some of this output will need to be placed in the comments to any pull request and pass review before that PR can be merged. 
   - Some of this output will need to be checked into the repo and to be compared against prior output.  See [webapp-public Issue #539](https://github.com/OpenSourcePolicyCenter/webapp-public/issues/539).
    - This step cannot be incorporated into Travis CI because the computation time takes too long for the equilibrium transition path.

@jdebacker @MattHJensen @hdoupe @PeterDSteinberg

**Comment by PeterDSteinberg** [comment] 2017-07-17 18:27
A couple of notes on the procedure above:

Regarding 3):
 * We will view the a paste of the regression test results into the github PR discussion as a requirement before merging, inclusive also of discussion related to divergence of the results from standards, if any, but on a case by case basis we may agree that a PR can be merged without the regression test results (e.g a documentation PR)

One more point on procedure from the meeting:
 * When writing tests and new code in OG-USA, try to follow PEP8 for new code, then around October 1 or so, let's revisit the idea of automated PEP8 check in the Travis CI, perhaps with some exceptions like Tax-Calculator has specified in its `setup.cfg`

Near term TODO list for this issue:
 * [ ] Finish the discussion on @rickecon started above on procedures, and then write out in a README markdown at top level of repo the procedure for how to create the standardized regression test results, what to paste into an PR, and any notes about configuration/setup/install for running that regression test suite.
 * [ ] Make a script that runs the regression test(s) so it is a simple one-liner ideally to make the standard regression test results, e.g. `source activate aei_dropq && python run_regression_test.py default_regression_reforms.json` or similar command.  I think we already have something like that in here we can modify.
 * [ ] Update Travis CI configuration to do the following now (I'll (Peter) do this part):
   * [ ] Use `conda build` and `conda install --use-local` as shown in the example [Earthio Travis build scripts here](https://github.com/ContinuumIO/earthio/blob/master/.travis.yml) and [here](https://github.com/ContinuumIO/earthio/blob/master/build_earthio_env.sh)
   * [ ] Loop over Python 2.7, 3.5, 3.6 in the Travis build matrix setup, but for now set the Python 3.X builds to expected failures/skips.  Make a reminder in .travis.yml for when we do the Python 3 compatibility PR merges to uncomment/undo whatever setting is setting the Python 3.X builds to skip.

@jdebacker Can you assign this issue to yourself mainly to make the README on regression testing and ensure we have a simple command line tool for running the typical regression tests.  I'll open a PR later this week with the Travis CI changes of the "Near term TODO" list above - let me know if I'm holding anybody up.

**Comment by jdebacker** [comment] 2017-07-17 18:43
Yes, @rickecon and I will spell out what the regression tests should contain and will put that in a README.

**Comment by hdoupe** [comment] 2017-07-17 18:55
I'm looking at the tests that we currently have in the `tests` directory.  Are you all comfortable with the tests that are already there?  Do we need to scrap any and start over there?

There are two places where I'm interested in getting started here.  

1. Break down the `run_micro_macro` function in `test_run_ogusa.py` into several functions so that the SS and TPI functionalities can be tested separately.  Then from there try to test functions on a lower level (ie `SS_solver`, `SS_fsolve`, `SS_fsolve_reform`, etc. ).  

2. Begin doing unit tests on modules like `household.py`, `firm.py`, `fiscal.py` etc.

What do you all think?  I'm pretty new to all of this and open to all suggestions and advice.  Just point me in the right direction and I'll get to work.

@rickecon @PeterDSteinberg @PeterDSteinberg

**Comment by jdebacker** [comment] 2017-07-17 19:21
@hdoupe let me outline what I understand and find useful in the current test infrastructure:

In `test_basic.py`:
- `test_run_small()` is something that's been useful to be sure the model runs through without error.  This test uses a scaled down version of the model to improve run time.
- `test_get_micro_data_get_calculator()` is helpful to be sure that the model plays well with the Tax-Calculator version that is used.  In particular, it checks that the format for the reform dictionary does  not cause an error.  This could probably be written more robustly to check not just the format of inputs, but also outputs.
- I'm not sure about all the test of pickle files here, but we did have some cross-platform issues early on so they may be related to that.

In `test_parameters.py`:
- Not sure what this is doing exactly.  

In `test_run_ogusa.py`:
- This runs the baseline and reform through to the computation of the final outputs (a table of percent differences between the baseline and reform policies for macro aggregates and prices).
- Like `test_basic.test_run_small()` this uses a scaled down version of the model and pre-estimated tax function parameters (i.e., `run_micro=False`).  Both these things improve run time.

In `test_sstpi.py`:
- Not sure what this does. Looks like it runs some version of the full model though.

I'm no expert on testing, but am happy to answer any questions about the model and offer suggestions on how to improve the speed of tests (either by scaling down the size of the state space or choosing parameterizations and starting values that will yield quick convergence). 

I generally like your idea of where to get started.  I'm not sure your preference, but my thought was that starting with the smaller functions and working out might be a good way to go because they are easier bites swallow and will help you understand things before moving up to the larger fruntions like `SS_fsolve` and `get_TPI`.

**Comment by hdoupe** [comment] 2017-07-17 19:49
@jdebacker Thanks, that's very helpful.  I'll get started on the smaller, less complex modules.

**Comment by jdebacker** [comment] 2018-04-25 15:04
I'm going to close this broad issue.  We now have 100+ unit tests and a decent regression testing harness.  We can use some more code coverage with the unit tests and we might be able to streamline the regression testing a bit, but we can discuss particulars in new issues.

**Closed by jdebacker** 2018-04-25 15:04 UTC
