### ISSUE TITLE
Regression testing for OG-USA

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/OG-USA#232] opened 2016-08-04 10:02 UTC
As OG-USA's user base grows, I think it will be extremely important to understand exactly when and why OG-USA results change. 

One way to facilitate this would be to add tests that run OG-USA for a number of well-chosen reforms and then checks the results of those reforms into the repo in a git-diffable format. 

Probably the tests should be triggered by every OG-USA PR and every taxcalc version change on TaxBrain. 

cc @talumbau, @rickecon, @jdebacker, @kerkphil, @martinholmer

**Comment by rickecon** [comment] 2016-08-04 13:56
I agree. Candidate reforms should probably include the 10-pct marginal income tax rate cut that we study in the "Integration..." working paper.

**Comment by MattHJensen** [comment] 2016-08-05 12:27
We had a pretty good set of ten or so before. Those might be a good starting point as well.

**Comment by jdebacker** [comment] 2016-08-05 12:40
I agree we need some more testing and to document changes in results (and to make sure the results don't change when they shouldn't).  But a couple things to keep in mind:

1. Model run time.  For the full blown model, doing a baseline and reform and estimating tax functions currently takes about 8+ hours.  We do plan to work on speeding up this run time, but one should bear this is in mind.  If doing multiple reforms, we'd certainly want to farm each out to a different AWS node.
2. Our git workflow.  Perhaps we can get better about this, but with the way we are doing things currently, if one were to run the model from what is in OSE/OG-USA:master, one would not likely get the results they think they are getting.  The reason is that as we add new features and test things, there is lots of commenting/uncommenting bits of code and these aren't always undone when merged to master (e.g. because we want to merge in one change to build something else off of it while keeping the "reduced" parameter set).  We could discuss how to change this methodology, but one idea to to just run the checks suggested in this issue before OG-USA updates are incorporated into TaxBrain and not for each PR to OSE/OG-USA:master.

**Comment by MattHJensen** [comment] 2016-08-06 06:59
> Model run time. For the full blown model, doing a baseline and reform and estimating tax functions currently takes about 8+ hours. We do plan to work on speeding up this run time, but one should bear this is in mind. If doing multiple reforms, we'd certainly want to farm each out to a different AWS node.

This is definitely a complication. @talumbau might have other ideas as well. 

> but one idea to to just run the checks suggested in this issue before OG-USA updates are incorporated into TaxBrain and not for each PR to OSE/OG-USA:master.

This would certainly be an improvement and tell us when the results have changed on TaxBrain. But do you think it would be sufficient to tell us exactly _why_ the results changed and the magnitude of change that different OG-USA or Tax-Calculator patches were responsible for? I think that information might be important to our users if they are relying on OG-USA for policy decisions.

**Comment by jdebacker** [comment] 2016-08-17 12:03
As an addition to this conversation, I think we should consider changing how we test OG-USA - we now have a better infrastructure to run a scaled down version of the model that can avoid the "execute_small" and the reduced parameter set.  

Essentially, we should be able to run a quick test by calling all the functions used to run the full model, but setting:
- S=40
- J = 1
- run_micro=False
- calibrate=False

With these settings, the SS will solve in seconds and the TPI in ~15 minutes.

**Comment by rickecon** [comment] 2016-08-17 15:12
I would recommend S=30 and J=2 (J is automatically set by inputting a lambdas matrix) by setting lambdas = np.array([0.6, 0.4]).

**Comment by talumbau** [comment] 2016-08-17 15:44
I have an idea on how to do this. Basically we would use a feature of github called webhooks to kick off a bunch of tests when a certain event happens on the OGUSA repo. This "event" could be "a PR gets merged to master" or it could also be "we just created a new release of OGUSA". Given Jason's comment above, it might make the most sense to use the latter as the qualifying event. Personally, I like the idea of "master is always in a releasable state", but we don't have to work that way. In order to do adhere to that rule, as two (or more) people are collaborating on code and going back and forth with changes, they have to agree on some other branch besides `master` to be the "home" for their merged changes. Usually, this branch will have a name related to the new feature they are collaborating on. If that branch is called `dev_feature`, for example, then Jason would work in `jason_feature` and periodically do PRs to `dev_feature`. Then, Rick would pull the latest `dev_feature` and merge those changes in to `rick_feature`. Rick would then continue to work in `rick_feature` until he is ready to share the changes, and then create a PR from `rick_feature` to `dev_feature` and so on. So, it's basically the workflow you are used to, but only using `master` when the code is ready for release. Something to consider.

But back to the testing itself. In some agreed upon way, I can configure a bunch of tests to run whenever some event happens on this repo. The main things I would need to know would be:

 - what is the qualifying event that should kick off these tests?
 - what reforms would you like to see run?
 - what output would you like to see for these runs? I don't think I could show you regular OGUSA TaxBrain output because I would actually have to release OGUSA to generate the output and this is about testing prior to releasing to TaxBrain.

Let me know your thoughts here @MattHJensen @rickecon @jdebacker

**Comment by jdebacker** [comment] 2016-08-17 16:16
I like the workflow that @talumbau suggests.  I agree that it's preferable to have the master in a releasable state and this seems like a way to solve that (other than me getting lost on where I am on git).

@talumbau , can we have two layers of testing. 
1) Something akin to the Travis CI test we currently have-  basically making sure code runs through with a model with a reduced state space. This would be kicked off with a PR to *any* branch of the OSE/OG-USA repo.
2) A test as proposed here that runs a series of reforms all the way through with the full model (including estimating tax functions).  These tests are intended to look for substantive changes in results from updates to the source code.  These tests are triggered when one wants to merge a PR to OSE/OG-USA:master.

I can put together a list of reforms.  We have 10 we used before that had different changes to top rates, lower rates, standard deduction.  So they cover changes at the top and bottom of the income distribution and changes that more heavily affect MTRs or ATRs.  

Re output, I had done tests like this before with spreadsheets.  Maybe we just want to keep the pickles each model run currently saves (one for SS, one for TPI).  Then we can put together a script to look at differences between items in these pickles and those from past versions (separately for each reform).  I think the first place to look would be at differences in the aggregates we report on TaxBrain.  So you could image a dictionary with keys that are each of the 10 reforms and values that are 2x7 arrays.  Each cell in the array is the difference between the value of the aggregate variable in the current version vs prior version.  The rows of these arrays will represent the different aggregate variable and the columns the tax years. 

I don't know what "passing the test" means.  It's subjective - depends what changed in the code.  So can we just get this output and then manually say "passes test".  

If not, how do we set up criteria?

**Comment by talumbau** [comment] 2016-08-17 16:30
@jdebacker item 1 in your list would involve use of the PUF, correct? If yes, then we would have to support this use case by ourselves. If not, then we could just add this to Travis CI.

**Comment by jdebacker** [comment] 2016-08-17 16:35
@talumbau , I think (1) wouldn't have to involve the PUF.  We could use a default pickle file with the tax function parameters (like we do now, I think).  (2) would involve running the TC.  Currently, this means running it with the PUF.  We might be able to write a get_micro_data.py that uses different variable names in case the PUF weren't used (though maybe that's not an issue and if the CPS (or other dataset) were used in the TC, the variable names are converted??).

**Comment by kerkphil** [comment] 2016-08-17 17:50
I'm with Jason. TJ's workflow sounds like the ideal best practice. It keeps master always working and still allows for efficient development. Sounds like all we need to do is remember to do all developmental PRs to the development fork instead of master. Even I would only screw that up occasionally.

**Comment by talumbau** [comment] 2016-08-17 18:00
good point about what is a "pass". For (1), the criterion is clear -correct? It would just be 'does it run through with the reduced parameters. For (2), it is inherently subjective, so the idea would be to create something such that any collaborator could log in or go to some specific URL that I would provide and see a basic chart of how the proposed code compares to the current release on the ten reforms. If the "trigger" event is done right, a collaborator could open a PR (or merge a PR, whatever we decide) say during the evening on one day, and then go check a URL the next morning to see the results of all of the runs. The URL would be shareable so anyone could just share the link and discuss the latest results. we are starting to drift towards use cases best handled by an existing tool like Jenkins, which is not a bad thing. It just means that the task becomes "configure this tool to do what we want" rather than "write some code to do what we want"

**Comment by jdebacker** [comment] 2016-08-17 18:22
Yes, criterion on (1) is "run through to completion".

**Comment by jdebacker** [comment] 2016-08-17 18:24
FYI, here are the 10 reforms I had run for testing in the past:

    reform0 = {
    2016: {
        '_II_rt1': [.09],
        '_II_rt2': [.135],
        '_II_rt3': [.225],
        '_II_rt4': [.252],
        '_II_rt5': [.297],
        '_II_rt6': [.315],
        '_II_rt7': [0.3564],
    }, }

    reform1 = {
    2016: {
        '_II_rt7': [0.35],
    }, }

    reform2 = {
    2016: {
        '_II_rt7': [0.34],
    }, }

    reform3 = {
    2016: {
        '_CG_rt3': [0.25],
    }, }

    reform4 = {
    2016: {
        '_CG_rt3': [0.24],
    }, }

    reform5 = {
    2016: {
        '_CG_rt3': [0.16],
    }, }

    reform6 = {
    2016: {
        '_STD': [ [6100*2, 12200*2, 6100*2, 8950*2, 12200*2, 6100*2, 1000*2], 
                    [6200*2, 12400*2, 6200*2, 9100*2, 12400*2, 6200*2, 1000*2],
                    [6300*2, 12600*2, 6300*2, 9250*2, 12600*2, 6300*2, 1050*2]],
    }, }  

    reform7 = {
    2016: {
        '_STD': [ [6100*2.1, 12200*2.1, 6100*2.1, 8950*2.1, 12200*2.1, 6100*2.1, 1000*2.1], 
                    [6200*2.1, 12400*2.1, 6200*2.1, 9100*2.1, 12400*2.1, 6200*2.1, 1000*2.1],
                    [6300*2.1, 12600*2.1, 6300*2.1, 9250*2.1, 12600*2.1, 6300*2.1, 1050*2.1]],
    }, }    

    reform8 = {
    2016: {
        '_II_rt3': [.15],
        '_II_rt4': [.15],
        '_II_rt5': [.15],
        '_II_brk5':[[250000, 250000, 125000, 250000, 250000, 250000]]
    }, }

    
    reform9 = {
    2016: {
            '_STD': [[12600, 25200, 12600, 18600, 25300, 12600, 2100]],
            '_II_brk1': [[27825, 55650, 27825, 39750, 55650, 27825]],
            '_II_brk2': [[65005, 130010, 65005, 88180, 130010, 65005]],
            '_AMT_trt1': [.0],
           '_AMT_trt2': [.0]
    },}

Again, somewhat arbitrary.  But they do cover a number of bases in terms of what changes with tax policy.

**Comment by MattHJensen** [comment] 2016-08-17 20:08
+1 on everything here too. 

For the final set of tests, what do you think about using the full model rather than the pared-down model so that we can see exactly what the 'official' results are at each point in development and why they have changed? Or perhaps we could do both if the 8 hour wait is too long to wait to merge a PR.

**Comment by rickecon** [comment] 2016-08-17 20:13
One thing we need to remember is that all PR's are not of the same significance. Some are cleanup, and some are augmentations. For cleanup PR's, we are probably fine running tests exclusively on the reduced size model. However, for significant augmentations of the model, it is probably valuable to do a set of tests on the full model. It is not clear to me how best to differentiate between these. However, it is essential to carefully test every PR in order to not introduce contaminating coding errors.

**Comment by jdebacker** [comment] 2016-08-17 20:19
@MattHJensen, yes, I would suggest layer (2) use the full model.

@rickecon, re the differences in PRs, one thing we could do is if the code change is not substantive (e.g. changes some commenting), we just leave it on the `dev_feature` branch - only only merge this to `master` when substantive changes have been added.  So the person with the PR can decide if it needs to be included in `master` (which would then trigger the more involved 2nd layer of testing).

**Comment by MattHJensen** [comment] 2016-08-17 20:22
Another option would be to have all PR's to master kick off the small model runs;  if the PR causes a change of key outputs from the small model, it automatically kicks off the full model run.

**Comment by jdebacker** [comment] 2018-11-16 15:15
I think we now how a pretty robust regression testing framework.  This can be expanded to include more cases of the model (currently it runs a number of reforms, but all for the closed economy, unbalanced budget configuration - we should also set up tests with open economy and different budget rules).  

But closing this issue sing I think most issues here have been addressed.

**Closed by jdebacker** 2018-11-16 15:15 UTC
Labels: in progress
